---
- name: Install latest haproxy
  apt:
   name: haproxy
   state: latest
   update_cache: yes

- name: Stop haproxy service
  service: 
   name: haproxy
   state: stopped
  ignore_errors: yes

- name: Add custom config
  copy: src=haproxy.cfg dest=/etc/haproxy/haproxy.cfg

- name: Enabling haproxy
  lineinfile:
    destfile: /etc/default/haproxy
    regexp: '^ENABLED'
    line: 'ENABLED=1'

- name: Start haproxy service
  service: state=restarted name=haproxy

